---
title: "**Code of Conduct**"
output:
  html_document
---
<!-- This document contains code of conduct details that appear multiple places. -->

<br>

We would like to create an open, safe, welcoming, diverse, inclusive, intellectually stimulating, and hopefully fun class experience. 

We strive to be a space in which individual differences are respected, so that each individual can reach their fullest potential.

This Code of Conduct applies to emails, surveys, Slack, Zoom, office hours, and meetings with other students, instructors, or CBO members.

<br>

### Guidelines

- Demonstrate empathy and kindness toward other people
- Give and gracefully accept constructive feedback
- Avoid making assumptions about others
- Be respectful of differing opinions, viewpoints, and experiences
- Take the time to consider how your speech and actions may influence others
- Actively seek to acknowledge and respect the boundaries of others
- If students are struggling with coursework or with their peers or others, please reach out to the instructors as early as possible
- **Please reach out to an instructor if you witness or experience a violation of the class guidelines or other JHU codes of conduct.**

<br>

### JHU CoC

- [JHU Student Code of Conduct](https://studentaffairs.jhu.edu/policies-guidelines/student-code/)
- [Hopkins School of Medicine](https://www.hopkinsmedicine.org/research/resources/offices-policies/OPC/Research_Integrity/som_code_of_conduct_04302020.pdf)
- [JHSPH Academic Ethics Code](https://www.jhsph.edu/offices-and-services/student-affairs/resources/student-policies/_documents/academic-ethics-code.pdf)

<br>

### Resources

**The University has developed avenues for reporting and for seeking help including:** 

- JHU Sexual Assault Helpline, 410-516-7333 (confidential) 
- Campus Safety and Security, 410-516-7777 
- University Sexual Assault Response and Prevention website 
- Johns Hopkins Compliance Hotline, 844-SPEAK2US (844-733-2528) 
- JHU Office of Institutional Equity 410-516-8075 (not confidential) 
- Johns Hopkins Student Assistance Program (JHSAP), 443-287-7000 
- University Health Services - Mental Health (UHS-MS), 410-955-1892 
- The Faculty and Staff Assistance Program (FASAP), 443-997-7000 
