default:
  course_name_long: "Baltimore Community Data Science (NUMBERS)"
  course_dates: "June 12-16 and 20-23, 2023"
  course_time: "**Friday 1:30- 3:00 PM EST**"
  final_due_date: "June 30th at 11:59pm ET"
  grades_due: "August 25"
  holiday: "In recognition of [Juneteenth](https://en.wikipedia.org/wiki/Juneteenth), there will be **no class on Monday June 19th, 2023**."
  courseplus_web: "https://courseplus.jhu.edu/core/index.cfm/go/syl:syl.public.view/coid/20767/"
  courseplus_dropboxes: "https://courseplus.jhu.edu/core/index.cfm/go/db:main/coID/20767/"
  courseplus_surveys: "https://courseplus.jhu.edu/core/index.cfm/go/survey2:admin.home/coID/20767/#!/"
  ta: "Rupshikha Sen (rsen6 at jhmi.edu)"
  instructors: "[Carrie Wright](https://carriewright11.github.io/) (cwrigh60 at jhu.edu), [Ava Hoffman](https://www.avahoffman.com/) (ava.hoffman at jhu.edu), [Clifton McKee](https://clifmckee.github.io/) (cmckee7 at jhu.edu)"
  r_version: "(4.3.0 (called 'Already Tomorrow') as of April 21, 2023)"
  r_dl_mac_m1: "https://cloud.r-project.org/bin/macosx/big-sur-arm64/base/R-4.3.0-arm64.pkg"
  r_dl_mac_intel: "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.0-x86_64.pkg"
  r_dl_windows: "https://cloud.r-project.org/bin/windows/base/R-4.3.0-win.exe"
  rstudio_dl_mac: "https://download1.rstudio.org/electron/macos/RStudio-2023.03.1-446.dmg"
  rstudio_dl_windows: "https://download1.rstudio.org/electron/windows/RStudio-2023.03.1-446.exe"

