default:
  course_name_long: "Baltimore Community Data Science (PH.140.801 + 802)"
  course_time: "**Friday 1:30 - 2:50pm ET**"
  instructor_1: "[Carrie Wright](https://carriewright11.github.io/) ([cwrigh60@jhu.edu](mailto:cwrigh60@jhu.edu))"
  instructor_2: "[Ava Hoffman](https://www.avahoffman.com/) ([ava.hoffman@jhu.edu](mailto:ava.hoffman@jhu.edu))"
  instructor_3: "[Michael Rosenblum](https://mrosenblumbiostat.wordpress.com/) ([mrosen@jhu.edu](mailto:mrosen@jhu.edu))"
  terms: "**1st and 2nd terms**"
  catalog_pt1: https://www.jhsph.edu/courses/course/38607/2023/140.801.01/baltimore-community-data-science
  catalog_pt1_dates: "Monday, August 25th - Monday, October 20th"
  term_dates_1:
    overall: "First"
    wk1: "8/29"
    wk2: "9/5"
    wk3: "9/12"
    wk4: "9/19"
    wk5: "9/26"
    wk6: "10/3"
    wk7: "10/10"
    wk8: "10/17"
  catalog_pt2: https://www.jhsph.edu/courses/course/38608/2023/140.802.01/baltimore-community-data-science-ii
  catalog_pt2_dates: "Wednesday, October 22 - Friday, December 19"
  term_dates_2:
    overall: "Second"
    wk1: "10/24"
    wk2: "10/31"
    wk3: "11/7"
    wk4: "11/14"
    wk5: "11/21"
    wk6: "12/5"
    wk7: "12/12"
    wk8: "12/19"
  acad_year: "2025-2026"
  grading_model: "**letter grade** or **pass/fail**"
