# Style any R code
style-code: no
# Check spelling
spell-check: yes
# Check that urls in the content are not broken
url-checker: no
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes
