---
title: "**Projects**"
output:
  html_document
---

Students will work in groups of 3-5 on projects with a community based organization (CBO). Students will work with the CBO to identify the **main priority project goals**, as well as to identify other goals would be of interest but are not the priority. Students should keep an open dialog with the CBO about what they think might possible for these additional goals, while being mindful about not over promising. 

Student groups should focus on the development of these main priorities and **seek feedback from the CBO** about if the project is meeting the intended goals. 

The projects are intended to **scale** based on the time and capacity available to the students working on the projects. If the main goals of the project are met, students can then work on additional project goals. 

### **Things to remember:** 

- As this is an extra difficult time for everyone due to the pressures of the pandemic, **try to practice patience** with the CBO members and your fellow project members. Remember that the CBO members have other priorities and may not be able to get back to you as quickly as you might expect. 

- Some of the CBO members may be new to data science and so **there will be a learning period** for you to explain what data products are possible. This may cause the **main project goals to evolve over time**. 

- Remember that **you are learning** about what the CBO does and about their goals. This may also cause the definition of the main project goals to evolve over time.

- **We will have misunderstandings** with each other and the CBO members. This is expected and part of the process. Try to **stay open to adapting** as we clarify our communications with one another.

- Keep the following [dos and don'ts](https://source.jhu.edu/publications-and-resources/DosAndDontsOfPartnerships.pdf) in mind from [SOURCE](https://source.jhu.edu).

<br>

```{r, echo = FALSE, out.width="100%"}
knitr::include_url(url = "https://source.jhu.edu/publications-and-resources/DosAndDontsOfPartnerships.pdf")
```

<br>
<br>


### **Examples of Data Science Products**

- **Data planning** - planning data collection so that it’s tailored to assist the needs of the CBO. This could include survey ethics, design, implementation, or future data analyses.
- **Data import** - working with the CBO partners to identify sources of data  and how to capture that data in a programmatic way. This could be scraping data from a website or importing data from an API.
- **Data wrangling/cleaning** - working with the data to get it in a format that is readily usable for creating  graphs, tables, and statistics. (This is often the most important step but often overlooked!)
- **Data visualization** - enabling partners to make highly flexible and effective visualizations to inform themselves and others about patterns in data.
Dashboard creation - showcasing results in a user-friendly way through a public facing website.
- **Data analysis** - identifying patterns about the data to assist with decision making processes and to assist with getting funding. 
- **Data communication** - assisting CBOs in how to interpret and describe trends in the data. This may involve speaking at an event for the CBO.
- **Shiny app** - automating some processes for the CBO with an app. See https://shiny.rstudio.com/gallery/ for examples.
- **GitHub actions** - another option for potentially automating processes for the CBO. 


### **Student Roles for Projects**

Students may end up taking on multiple critical roles for the projects. Furthermore, students can play a different role for different phases of the project.

#### **Leadership Roles:**

* **Results Manager** - This student will ensure that project development timelines are being met by developing milestones and tracking project process.

* **Communication Lead** - This student is the main point of contact for the group to interact with one another, interact with the CBO, and interact with instructors.

* **Sustainability Lead** - This student will help identify and coordinate with the future handlers of the data science product at the partner organization. They will identify key areas for partner education and training.

* **Project Lead** - This student will make sure that all group members are enjoying their role(s) and are being productive in their role(s). They will consider how each member works and where collaboration can be improved if possible. They will also be in charge of considering the big picture goals of the project as a whole.

#### **Technical Roles:**

* **Infrastructure/Organization Lead** - This student is in charge of organizing and maintaining a file structure for the documentation, notes, communication, code, etc. for the project. (We will provide workflow suggestions for this - it will largely involve GitHub.)


* **Documentation Lead** - This student will take notes at meetings and create documentation text about how to contribute to projects and descriptions for others about the project.


* **Development Lead** - This student will manage the production of the code / code standards by assigning themselves and delegating to others to various code-related tasks.


* **Design/Aesthetics Lead** - This student will manage aesthetic or design related aspects for the project, including visualizations and graphics for documentation, apps, and other content readable, engaging, and appropriate for the given audience.
