---
title: "**Resources**"
output:
  html_document
---

The following resources may be helpful to students as they work on their projects with one another. 

### **Assignment Resources**

<div class = table_style>
|Topic| Resource| Use |
|-------------------|--------------------|--------------------|
|Guidelines for Critical Reflection | [Course Guide to Critical Reflection](https://docs.google.com/document/d/10dM6WA2LHmX922-hlehJULX5IWSizsH6kWnNAVe_VYw/edit?usp=sharing)| This guide can help you to think about prompts in different ways and remind you of good practices.|
|Critical Reflection Journal| [Reflection Journal Template](https://docs.google.com/document/d/16FIPvK3MI3Jd_TKcGoklysANy1aqbkw7BjhlcJnFva8/edit?usp=sharing)| This template can serve as an example for how to structure your reflection journal.Please submit your journal using this [form](https://forms.gle/m67DyJNsehYB8qnSA)|
|Slack Discussions|[Contributing to Slack Discussions](https://docs.google.com/document/d/1Wh01tDp_JFbwE1EDRcONXfjFJIpuLNbcQJAW9W1ALbk/edit?usp=sharing)| This document has instructions for how to participate in an asynchronous class discussion using Slack.|
</div>

### **Critical Service Learning Resources**
<div class = table_style>
|Topic| Resource| Use |
|-------------------|--------------------|--------------------|
|SOURCE - the community engagement and service-learning center at the Johns Hopkins Bloomberg School of Public health| * [SOURCE website](https://source.jhu.edu/) <br> * [SOURCE resources](https://source.jhu.edu/publications-and-resources/national-resources.html) <br> * [Service Opportunities](https://source.jhu.edu/audiences/students/opportunities/index.html)| SOURCE has lots of valuable resources on the philosophy of critical service learning, as well as  information on other ways to engage with the community|
|Course reading material | [Course assignments and extra reading resources](https://jhudatascience.org/Baltimore_Community_Course/schedule.html) | Please see the course schedule for additional resources about the history of Baltimore and the US, as well as reading material about the basis of critical service learning.|
</div>



### **Baltimore Resources**
<div class = table_style>
|Topic| Resource| Use |
|-------------------|--------------------|--------------------|
|Baltimore Neighborhood Indicators Alliance (BNIA) Resources| * [Learning Modules](https://bniajfi.org/resources/learning-community/for-instructors/faculty-resources/downloads/) <br> * [BNIA Data](https://bniajfi.org/vital_signs/data_downloads/) <br> *[GIS mapping resources](https://mapping-bniajfi.opendata.arcgis.com/)| BNIA has data,learning modules, and information related to Baltimore Neighborhoods|
General information |[SOURCE Baltimore Information](https://source.jhu.edu/audiences/students/know-baltimore/index.html)| Learn more about the Baltimore community|
</div>

### **Project Planning and Infrastructure Resources**

<div class = table_style>
|Topic| Resource| Use|
|-------------------|--------------------|--------------------|
|Project Organization and Resources | [Suggestions for project planning and Resources](https://docs.google.com/document/d/1RveTbckBTomgx2JiiCbm01SE88OvODK7JCQxo1gbLbo/edit?usp=sharing)| Thoughts about how to track communications, take notes, share files, create timelines and other graphics, write code, and work on GitHub together. You are allowed to use other options, but this should help get you started.| 
|Project template form | [Form to aid planning discussions](https://docs.google.com/document/d/1b0XHuKsys_ACCtA9nI_M9F1CR2oWo2RLR-A1C6cvz0U/edit?usp=sharing) | This form will help the group document and make important planning decisions about the project.|
</div>


### **R Resources**

<div class = table_style>
|Topic| Resource| Use |
|-------------------|--------------------|--------------------|
|Dashboards|[School Shooting Open Case Study](https://www.opencasestudies.org/ocs-bp-school-shootings-dashboard/)[Data visualization and organization branding](https://rfortherestofus.com/2022/02/data-viz-org-branding/)| Dashboards can be a great way to demonstrate many aspects about a data set efficiently. They can help tell a data story. 
|Data Visualization| [Data visualization and organization branding](https://rfortherestofus.com/2022/02/data-viz-org-branding/)| R has many opportunities for customizing visualizations to the organization's needs.|
|Extracting text from images|[Youth Disconnection Open Case Study](https://www.opencasestudies.org/ocs-bp-youth-disconnection/)| You might  find that you need to import text from image files.|
|Importing data from an API|[Opioid Case Study](https://www.opencasestudies.org/ocs-bp-opioid-rural-urban/)| Some common websites (like many social media websites) have APIs that allow you to access data.|
|Importing multiple files| [Vaping Behaviors Case Study](https://www.opencasestudies.org/ocs-bp-vaping-case-study/#Data_Import)|It can be helpful to programmatically import files efficiently using fewer steps.|
|Sentiment analysis| [tidytextmining](https://www.tidytextmining.com/sentiment.html)| Sentiment analysis can be useful for understanding the "emotional intent" of text data.|
</div>

### **Git and GitHub Resources**

<div class = table_style>
|Topic| Resource| Use|
|-------------------|--------------------|--------------------|
|General Resource | [Happy Git and GitHub for the use R ](https://happygitwithr.com/)| Git and GitHub are great for version control to ensure that you don't lose any of your work and you can clearly see how your code (or other files) changed  over time|
|Reproducibility & GitHub Actions | [ITN Advanced Reproducibility Course ](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/)| GitHub Actions can help you to automate aspects about your work. It is especially helpful when you are rendering files and working with a team.|
</div>





