---
title: "**Course Schedule**"
output:
  html_document
---

### **Daily**

Every class session will start and end with a writing prompt that will be used for class discussions. This course will involve some lectures and speakers, but will largely involve writing exercises, discussion/reflection activities, and teamwork on the data science project. We want to cultivate a culture that respects all viewpoints and values all experiences, where there are complicated answers, and where a growth mindset is upheld.

### **Weekly**

- **Week 1-5** - will focus on training and guidance about how our work fits into the greater context of Baltimore, understanding what the CBOs do and why, as well as some instruction on data security, privacy, and ethics 
- **Week 6-10** - will focus on working on the data science product(s) (**Week 8 - meeting with CBO to check in overall, as well as individual meetings with instructors**)
- **Week 11-13** - will focus on plans for implementation, sustainability/maintenance, and optionally training
- **Week 14 -16** - will focus on reflection on the implementation, lessons learned, and future ideas - final report

### **Class Sessions**{.tabset .tabset-fade}

#### **Third Term**{.tabset .tabset-fade}

##### **Week 1**

**Course and Context - Historical and Present**


<div class = "table_style">
|**Summary**| **Content** |**Homework <br> (please do before week 2)**|**Resources**|
|-----------|---------|----------------|-----------------|
|This week will focus on the **rationale**, **structure**, **philosophy**, and **goals** of the course. <br> We will also examine resources and discuss how the **historical and current context** of Johns Hopkins in the Baltimore Community may influence our work. |* [SOURCE Module 1: How History Impacts Our Work](https://courseplus.jhu.edu/core/index.cfm/go/course.home/coid/8136/)| * [Black Butterfly Academy: Baltimore Apartheid](https://jhubiostatistics.shinyapps.io/Baltimore_Apartheid/) <br> * [Mitigating Bias Training](https://jhudatascience.org/Baltimore_Community_Course/Assignments/Mitigating_Bias_Assignment.html) |**Extra Reading About History:** <br> * [Greenwood Tulsa Massacre](https://www.nytimes.com/interactive/2021/05/24/us/tulsa-race-massacre.html)<br> * [Rosewood Massacre](https://en.wikipedia.org/wiki/Rosewood_massacre) <br> * [Red Summer](https://en.wikipedia.org/wiki/Red_Summer) <br> * [Not in My Neighborhood: How Bigotry Shaped a Great American City](https://www.anteropietila.com/not-in-my-neighborhood) <br> * [Henrietta Lacks: science must right a historical wrong](https://www.nature.com/articles/d41586-020-02494-z) <br> **Extra Reading About Bias:** <br> * [Discrimination in Workplace Dynamics: Toward a Structural Account of Disparate Treatment Theory](http://web.archive.org/web/20120218231339/http://www.law.harvard.edu/students/orgs/crcl/vol38_1/green.pdf)|
</div>


##### **Week 2**

**Critical Service Learning**

<div class = "table_style">
|**Summary**| **Homework <br> (please do before  week 3)**|**Resources**|
|----------------|----------------|-----------------|
|This week Tyler Derreth, the Associate Director of [SOURCE](https://source.jhu.edu), will discuss what critical service learning is and how it differs from other forms of service. | [Traditional vs Critical Service Learning](https://jhudatascience.org/Baltimore_Community_Course/Assignments/Critical_Service_Learning_Assignment.html) |* [Product or Process? Reciprocity or Solidarity](https://files.eric.ed.gov/fulltext/EJ1163945.pdf)  <br> * [Theoretical roots of CSL](https://quod.lib.umich.edu/m/mjcsl/3239521.0001.109/1) <br> * [A case study of CSL](https://www.tandfonline.com/doi/full/10.1080/10665680701228797) <br> * [SOURCE Dos and don'ts](https://source.jhu.edu/publications-and-resources/DosAndDontsOfPartnerships.pdf)|
</div>

##### **Week 3**

**Critical Reflection Practices**

<div class = "table_style">
|**Summary**| **Content** |**Homework <br> (please do before week 4)**|**Resources**|
|---------------|------------|---------------|---------------|
|This week we will discuss how and why there is a focus on social and historical context and not just the data science for this course.  We will talk about how this context can or perhaps should influence how we perform the data science tasks planned and how we interact with community partners.|* [What is critical reflection?](https://www.dso.ufl.edu/documents/nsfp/What_is_Critical_Reflection.pdf) <br> * [Example Rubric for Reflection](https://uwaterloo.ca/centre-for-teaching-excellence/sites/ca.centre-for-teaching-excellence/files/uploads/files/critreflectrubric_trevor_holmes.pdf) <br> * [Models of reflection](https://uwaterloo.ca/centre-for-teaching-excellence/resources/reflection-framework-and-prompts#borton) <br> * [Course Guide to Critical Reflection](https://docs.google.com/document/d/10dM6WA2LHmX922-hlehJULX5IWSizsH6kWnNAVe_VYw/edit?usp=sharing)| * [Approaching Critical Service-Learning Assignment ](https://jhudatascience.org/Baltimore_Community_Course/Assignments/Approaching_Critical_Service_Learning_Assignment.html)  <br> * [Critical Reflection Review Assignment](https://jhudatascience.org/Baltimore_Community_Course/Assignments/Critical_Reflection_Review_Assignment.html) |**Extra Reading:** <br> * [Critical Reflective Practice](https://www.kent.ac.uk/teaching/documents/academic-practice/New%20to%20teaching%20Staff/Brookfield%20models%20of%20reflective%20practice.pdf)  <br> * [Critical Reflection in Higher Education Review](https://www.sciencedirect.com/science/article/pii/S1747938X20308368) <br> **Extra Videos:** <br>* ["What, So What, Now What" Model video](https://youtu.be/vGyjF9Ngd8Y) <br> * [Understanding reflective practice video](https://youtu.be/iBmtH0Qx0YU) <br>|
</div>

##### **Week 4**

**Project Planning and Forecasting**

<div class = "table_style">
|**Summary**| **Content** |**Homework <br> (please do before next week)**|**Resources**|
|--------------|------------|-------------|--------------|
|This week we will discuss more specifically about how students will **interact** with partners, as well as examples of what has and has not worked well in past similar projects. Students will meet with their **project group** for the first time and start assigning **student roles**.|* [Project planning form](https://docs.google.com/document/d/1b0XHuKsys_ACCtA9nI_M9F1CR2oWo2RLR-A1C6cvz0U/edit?usp=sharing) <br> * [Project organization and infrastructure suggestions](https://docs.google.com/document/d/1RveTbckBTomgx2JiiCbm01SE88OvODK7JCQxo1gbLbo/edit?usp=sharing)  | * [CBO Research and Reflection Assignment](CBO Research and Reflection Assignment)<br> * [Git & GitHub Assignment](https://jhudatascience.org/Baltimore_Community_Course/Assignments/Using_git_Assignment.html) |  * [SOURCE Dos and don'ts](https://source.jhu.edu/publications-and-resources/DosAndDontsOfPartnerships.pdf) <br> * [Project Student Roles](https://jhudatascience.org/Baltimore_Community_Course/projects.html/) <br> * [Project Reminders](https://jhudatascience.org/Baltimore_Community_Course/Projects.html/)|
</div>

##### **Week 5**

**Reproducibility & Data Security/Privacy/Ethics**

<div class = "table_style">
|**Summary**|  **Content** |**Homework <br> (please do before next week)**|**Resources**|
|----------------|----------------|-----------------|-----------------|
|This week we will discuss topics related to reproducibility, as well as data privacy, security, and ethics and how we can incorporate best practices into our projects. We will also discuss updates about each project.|[Version Control with GitHub (slides)](https://docs.google.com/presentation/d/1zd-UWGc03ltSFYlri2thQnCfojCHiQGsh6qdVSqn3Nk/edit?usp=sharing) |Assignments coming...|* [Intro Reproducibility Course (check back soon if link is broken)](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/) <br> * [Advanced Reproducibility Course](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/)|
</div>

##### **Week 6-8**

**Critical reflection and updates**

<div class = "table_style">
|**Summary**| **Homework <br> (please do before next week)**|**Resources**|
|----------------|----------------|-----------------|
|These weeks we will reflect on the challenges of our projects and give updates on how the project is going and how we are interacting with our community partners.**Check in with the CBO!**|Assignments coming...|* Resource Coming <br> * Resource Coming|
</div>


#### **Forth Term**
<div class = "table_style">
|**Time**|**Focus**|**Resources**|**Summary**|
|:-----------:|:------------------:|---------------------------|--------------------------|
|**Week 1 -2**|Critical reflection and updates|* Resource Coming <br> * Resource Coming|These weeks we will reflect on the challenges of our projects and give updates on how the project is going and how we are interacting with our community partners.|
|**Week 3-6**|Critical reflection and updates with emphasis on implementation, sustainability, and training plans| * Resource Coming <br> * Resource Coming|These weeks we will especially focus on how the community partners will use the data project product and how they might sustain the product over time, as well as work on training guides for the community partners if they asked for it.|
|**Week 7-8**|Implementation reflection and updates| * Resource Coming <br> * Resource Coming| This week we will focus on how the implementation is going, lessons learned, and thoughts about future directions for the community organization and for careers for students. |

</div>
