---
title: '**Baltimore Community Data Science (PH140.840) Syllabus**'
output:
  pdf_document: default
  html_document: default
---

<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->


<!-- <a href="syllabus.pdf" target="_blank" download = "syllabus.pdf"  ><button class="btn"><i class="fas fa-file-alt"></i> PDF version</button></a> -->



### Course Description

This course is focused on helping students learn how to apply their data science knowledge in non-academic settings. Students will partner with community-based organizations (CBOs) in Baltimore to work on a data science related goal. Students will focus on developing critical service-learning and professional skills as they work with CBOs to accomplish a data science related goal.


### Important Links

- **Class Website:** https://jhudatascience.org/Baltimore_Community_Course 
- **CoursePlus:** coming...
- **Zoom link** - will be emailed to registered students




### Logistics


* **Date:** The course will meet on **Fridays** during 1st and 2nd terms (1.5 credits each term).  
Students who take the class need to commit to **both** terms (for continuity of the projects they will work on).
    + [First term dates](https://publichealth.jhu.edu/academics/academic-calendar/2023-2024): Monday, August 28 - Monday, October 23
  * [Second term dates](https://publichealth.jhu.edu/academics/academic-calendar/2023-2024): 	Wednesday, October 25 - Friday, December 22
- **Time:** 1:30-2:50 PM EST
- **Location:** Students will meet in class (virtually) once per week. Students will work in groups outside of class on community-based projects virtually on zoom.
- **How often will students and CBOs meet?**
This depends on the project goals, but approximately 30 min - 1 hr every 2 weeks for the duration of the terms. Meetings will also be supplemented by emails. Keep in mind that CBO members are busy and staff may not be getting paid for their work.

**Communication will mainly occur through Slack and we will email you about how to connect to Slack.**

### Instructors

* Carrie Wright
    + website: https://carriewright11.github.io/
    + email: cwrigh60 at jhu.edu
* Ava Hoffman
    + website: https://www.avahoffman.com/ 
    + email: ava.hoffman at jhu.edu
* Michael Rosenblum
    + website: https://mrosenblumbiostat.wordpress.com/
    + email: mrosen at jhu.edu



### Requirements

Students are required to have some prior experience with R programming (or other languages). 

Instructor permission is required to enroll in the course. 

### Expectations of Students
 
Students will work with CBO partners as a team (3-5) for the following deliverables:

- learn about the partner CBO, the goals of the CBO, and how data may be helpful for these goals
- discuss the data needs of the create a plan to work with the CBO
- Create a data science product that aligns with the goals of the CBO
- Create an implementation plan and training for the CBO
- Create a sustainability plan for the CBO to work with and continue to maintain the data science product respectively including narratives ("story") about the data product - what it means, the limitations etc.
- Additional possible training and thoughts for CBO partners on further future data-related initiatives

In addition to working on data science projects, students are also expected to individually hone their critical service-learning skills and professional skills. This involves participating in written exercises and discussions, as well as active work to stay organized and maintain communication with teammates and the CBO. 

See the [project page](https://jhudatascience.org/Baltimore_Community_Course/projects.html) for more information about project guidelines.

### Expectations of CBOs

Partners will need to provide students with details on the project goals and uses, access to relevant data (could be de-identified or simulated if privacy is an issue), feedback about whether their goals are being met, and time and willingness to learn about how to use and possibly maintain the data product that the students work with them to create.

### Student Learning Objectives

Students who complete the course will be able to:

1) Describe the history of Johns Hopkins and the biostatistics department in the Baltimore community.  Evaluate and discuss how this **historical context** and the **current context** influences our interactions with community members.
2) **Critically reflect** on their own service-learning project work and how their role as a statistician impacts the CBO, as well as the greater context of society and social structures (not just the course project).
3) Articulate what **critical service-learning** is and describe how it differs from traditional community service endeavors. Evaluate and discuss how other methods can cause harm to communities.
4) Understand more about how to successfully **navigate challenges** that occur when applying data cleaning, wrangling, analysis, collection planning, visualization, and communication skills to problems in **non-academic settings**, as the students **create** (with the guidance and help of the CBO) **data science products** for the goals of the assigned CBO project. 
5) Work with others to **create an implementation plan** for the data science products that is viable and useful for the respective CBO members. Work with stakeholders at a high level to understand their needs as well as the limitations of the data.
6) Use teaching methods to **teach others** from various backgrounds and experiences  to use data science techniques to work with data and communicate effectively about data. 
7) Plan for CBO to continue to work with data science products in a **sustainable way** even after projects are over.


<!-- ```{r, child="code_of_conduct.Rmd"} -->

<!-- ``` -->

<!-- ```{r, child="evaluation.Rmd"} -->

<!-- ``` -->
