---
title: "Approaching Critical Service-Learning Assignment"
output: html_document
---


First, read this [article](https://files.eric.ed.gov/fulltext/EJ1182836.pdf):

Latta, Mark, Tina M Kruger, Lindsey Payne, Laura Weaver, and Jennifer L VanSickle. 2018. "Approaching Critical Service-Learning: A Model for Reflection On Positionality and Possibility. Journal of Higher Education Outreach and Engagement 22 (2): 31.

Choose one of the following prompts to respond to on Slack and be sure to respond to at least one other student response. Journal about the other prompt.

1) The article talks about how the intersections of our "multiple selves" and our positionality can influence our ability to successfully perform Critical Service Learning. Take a moment to reflect on how your identity of "multiple selves" and your position in society and our community may influence your perspective on the projects that you are about to embark on. What is your identity?  What are your "multiple selves"? How might your identity and position influence the project in positive or negative ways?

2) Take a look at Figure 1 in the article. How has your perspective on the process of critical service learning changed since the beginning of class? In what new ways do you think you will participate in the project that you might not have done if we had not discussed and reflected on critical service learning? How do you think the process might reflect the description in Figure 1?
