---
title: "Critical Service-Learning Assignment"
output: html_document
---

For this assignment you will need to have first read the following [paper](https://files.eric.ed.gov/fulltext/EJ831374.pdf): Traditional vs. Critical Service-Learning: Engaging the Literature to Differentiate Two Models, by Tania D. Mitchell

**Reflection Questions:**

Journal about the following prompt:  (In your responses aim to be thorough, novel, and authentic.)

1) Pick one of the partner organizations that we have discussed and do the following:
i. concisely define the problem/challenge that they are addressing;
ii. give an example of a structural determinant (i.e., cultural norm, policy, institution, law, or practice) of the problem/challenge. I.e., what is one of the root causes of the challenge/problem. Be as specific as possible, and give reasons/evidence for your claim(s).
You might start by reading material on the websites of the partner organization, e.g., in their mission statement for (i) and look at other parts for (ii).
Write at most 3 paragraphs. 


Journal about the following prompt **and** write a response to the discussion thread on Slack. Additionally, respond to at least one response from another student on the discussion thread on Slack.

2) What are some things (2-3) to keep in mind or put into practice to help ensure service-learning activities are working for social change? You can give general responses (that apply to many types of service-learning activities) or you can give specific responses tailored to the problem/challenge that you identified in problem 1, part (i).
