---
title: "Mitigating Bias Assignment"
output: html_document
---

Throughout this course you will interact with people with backgrounds and life experiences that may be different from your own. Thus we would like you to be aware of how our biases may influence our interactions. 

For this assignment you will need to complete a JHU training module. To access this module do the following:

1) Go to https://learning.jhu.edu/ and log in to your JHU account.

2) Search for "Managing Bias" in the catalog search

3) Add the course to your development plan

4) Select this course from your to do list to go to the course


After completing the module, return here to think about the following questions. 

**Reflection Questions:**

Journal about 2 (your choice) and write a response to the discussion thread on Slack for one prompt (your choice). Additionally, respond to at least one response from another student.


1) Think about an experience where you recognized yourself being biased (negative or positive/ implicit or explicit) towards another person. Describe what happened and how this may have impacted others.  Think about how you could avoid this in the future. If your bias was positive, think about why you may or may not want to avoid this bias.

2) Describe one thing in the training that surprised you.


3) Practicing awareness for bias can help us to recognize this metal shortcut process.

Think about another example like the seaweed/plant example below where you have witnessed humans making a mental shortcut.

“For example, a person might look at a piece of seaweed and think it’s a plant, because it has properties we associate with plants: its green color, leaves, and a stalk. In fact, seaweed isn’t a plant. But for most people in most situations, connecting seaweed to "plant" is “good enough,” even if it’s not true.”
 
4) Think of an example of a time when having a team member or coworker with a different perspective was helpful for solving a problem.
